version: '3'
services:
  web:
    build: web/
    ports:
      - 3001:80
    depends_on:
      - server
  server:
    build: server/
    ports:
      - "3000:80"
    links:
      - "redis"
    environment:
      - PORT=80
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    build: redis/
    ports:
      - "6379:6379"
