version: '3'
services:
  web:
    build: web/
    image: localhost:5000/redischat_web
    ports:
      - 3001:80
    depends_on:
      - api
    deploy:
      replicas: 1
  api:
    build: api/
    image: localhost:5000/redischat_api
    ports:
      - "3000:80"
    links:
      - "redis"
    environment:
      - PORT=80
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  redis:
    build: redis/
    image: localhost:5000/redischat_redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
