version: '3'
services:
  web:
    build: ./web/
    image: dolphub/redischat_web
    ports:
      - 3001:3001
  # api:
  #   build: api/
  #   image: dolphub/redischat_api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - REDIS_PORT=6379
  #     - REDIS_HOST=redis
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
