version: '3'
services:
  server:
    build: app/
    ports:
      - "3001:3001"
    links:
      - "redis"
    environment:
      - PORT=3001
      - REDIS_PORT=6379
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # armv7 
  #redis:
  #  image: "mangoraft/redis-arm"
  #  environment:
  #    - REDIS_PASS=**None**
  #  ports:
  #    - "6379:6379"
