version: '3'
services:
  app:
    build: app/
    ports:
      - "3001:3001"
    links:
      - "redis"
    environment:
      - PORT=3001
      - REDIS_PORT=6379
      - REDIS_HOST=redis # Docker dns provides redis host to redis container
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
